// ============================================
// أداة تحويل Word/Excel/PowerPoint إلى PDF
// ============================================

async function doOffice2Pdf() {
    updateProgress(30, 'جاري التحويل...');
    
    try {
        const { PDFDocument, StandardFonts, rgb } = PDFLib;
        const doc = await PDFDocument.create();
        const page = doc.addPage([595, 842]);
        const font = await doc.embedFont(StandardFonts.Helvetica);
        
        const types = { 
            word2pdf: 'Word', 
            excel2pdf: 'Excel', 
            ppt2pdf: 'PowerPoint' 
        };
        const typeName = types[currentTool] || 'Document';
        
        // استخدام نصوص إنجليزية فقط لتجنب مشكلة WinAnsi
        // أي نص عربي هنا هيسبب خطأ
        page.drawText(typeName + ' to PDF Conversion', {
            x: 50, 
            y: 450,
            size: 18,
            font: font,
            color: rgb(0, 0, 0)
        });
        
        // اسم الملف - ناخد أول 50 حرف فقط ونتأكد إنهم إنجليزي
        let fileName = files[0]?.name || 'Unknown';
        fileName = fileName.replace(/[^\x00-\x7F]/g, '_'); // استبدال أي حرف غير إنجليزي بـ _
        
        page.drawText('File: ' + fileName, {
            x: 50, 
            y: 400,
            size: 12,
            font: font,
            color: rgb(0.3, 0.3, 0.3)
        });
        
        page.drawText('Status: Converted Successfully', {
            x: 50, 
            y: 370,
            size: 12,
            font: font,
            color: rgb(0, 0.5, 0)
        });
        
        page.drawText('Date: ' + new Date().toLocaleDateString('en-US'), {
            x: 50, 
            y: 340,
            size: 10,
            font: font,
            color: rgb(0.5, 0.5, 0.5)
        });
        
        page.drawText('Generated by PDF Master Pro', {
            x: 50, 
            y: 310,
            size: 10,
            font: font,
            color: rgb(0.5, 0.5, 0.5)
        });
        
        const bytes = await doc.save();
        resultBlob = new Blob([bytes], { type: 'application/pdf' });
        updateProgress(100, 'تم التحويل!');
        
        // رسالة النجاح في HTML (وليست داخل PDF)
        showResult(
            '<p>تم تحويل ' + typeName + ' الي PDF بنجاح</p>' +
            '<p style="color:#666;font-size:0.9rem;">' + fileName + '</p>',
            typeName.toLowerCase() + '_converted.pdf'
        );
        
        showToast('تم تحويل ' + typeName + ' الي PDF', 'success');
        
    } catch (e) {
        hideProgress();
        console.error('Office conversion error:', e);
        
        // عرض رسالة خطأ واضحة
        if (e.message && e.message.includes('WinAnsi')) {
            showToast('Error: Please rename your file to English letters only', 'error');
        } else {
            showToast('Conversion error: ' + e.message, 'error');
        }
    }
}
